import { CURRENT_PATCH, VERIFIED_AT, profileSource } from './domain';
import type { Disc, Engine, BuildVariant } from './domain';
import { agents } from './catalog';
import { teams } from './service-data';
const discRows=[['king-summit','King of the Summit','Stun support','Daze','Team CRIT DMG with a CRIT Rate requirement'],['moonlight-lullaby','Moonlight Lullaby','Support','Energy Regen','Squad damage buff triggered by EX Special or Ultimate'],['astral-voice','Astral Voice','Assist support','ATK','Quick Assist-driven squad buff'],['hormone-punk','Hormone Punk','Burst','ATK','Timed ATK buff after entering combat or switching in'],['yunkui-tales','Yunkui Tales','Rupture','HP','Stacking CRIT Rate and Sheer damage'],['thorned-rose','Thorned Rose','Armorer','DEF','Armorer-specific Sharp damage bonuses'],['feathered-fate','Feathered Fate','Anomaly','Anomaly Proficiency','Attribute Anomaly damage after switching in'],['notes-chained','Notes From the Chained','Ice Anomaly','Anomaly Mastery','Freeze and Abloom conditions'],['phaethon-melody',"Phaethon's Melody",'Anomaly','Anomaly Mastery','EX-driven Anomaly Proficiency support']];
const sourceIds=['anby','nicole','astra-yao','sigrid','yixuan','claret','remielle','promeia','promeia'];
export const extraDiscs:Disc[]=discRows.map(([id,name,focus,twoPiece,fourPiece],i)=>({id,name,kind:'disc',focus,twoPiece,fourPiece,summary:`${focus} set.`,patch:CURRENT_PATCH,status:'verified',related:[],tags:[focus],source:profileSource(sourceIds[i]),verifiedAt:VERIFIED_AT,details:[`Two-piece focus: ${twoPiece}.`,`Four-piece focus: ${fourPiece}. Read the source for exact values and conditions.`]}));
export const extraEngines:Engine[]=[{id:'puzzle-sphere',kind:'engine',name:'Puzzle Sphere',specialty:'Rupture',rank:'A',access:'Gadget Store',summary:'Craftable Rupture candidate; its low-HP target condition matters in mode comparisons.',patch:CURRENT_PATCH,status:'verified',tags:['Rupture','Gadget Store'],related:['yixuan'],source:profileSource('yixuan'),verifiedAt:VERIFIED_AT}];
// Rows are equipment starting points, not a global ranking. Each has a reviewed profile source.
const rows:[string,string,string,string,string,string,string,string][]=[
 ['anby','steam-oven','king-summit','shockstar-disco','CRIT Rate','Electric DMG / ATK','Impact','Build Daze with her third Basic and EX follow-up. Avoid resetting the string before the useful hit.'],
 ['nicole','vault','moonlight-lullaby','hormone-punk','ATK / Anomaly Proficiency','Ether DMG / ATK','Energy Regen / ATK','Apply her grouping and defense debuff immediately before the carry’s attacks. A long setup can waste a short debuff window.'],
 ['nekomata','starlight-engine','woodpecker-electro','puffer-electro','CRIT Rate / CRIT DMG','PEN / ATK / Physical DMG','ATK','Use Dodge Counter or Quick Assist to establish her damage buff; manage current Potential resources instead of following release-era strings.'],
 ['lycaon','restrained','king-summit','shockstar-disco','CRIT Rate','Ice DMG / ATK','Impact','Establish Ice support and Daze before handing off. Do not keep a stun specialist active while the prepared carry window expires.'],
 ['rina','swing-cannon','moonlight-lullaby','puffer-electro','ATK / Anomaly Proficiency / CRIT Rate','PEN Ratio','Energy Regen','Refresh the puppets and PEN support, then return to the damage dealer. Current Potential changes alter puppet uptime.'],
 ['corin','starlight-engine','hormone-punk','woodpecker-electro','CRIT Rate','PEN / ATK / Physical DMG','ATK','Concentrate the long saw attacks inside a safe stun window. Time entering the field to the Hormone Punk cooldown.'],
 ['koleda','steam-oven','king-summit','shockstar-disco','CRIT Rate','Fire DMG / ATK','Impact','Prepare enhanced hits and rapid EX Daze; release the field to the carry after the stun setup. Armorer teams prefer a compatible support set.'],
 ['ben','original-transmorpher','woodpecker-electro','branch-blade','CRIT Rate / CRIT DMG','Fire DMG / PEN','ATK','Use timed blocks into counterattacks. This offensive Disc plan is distinct from maximizing protection; the defensive engine is an accessible utility candidate.'],
 ['anton','starlight-engine','thunder-metal','puffer-electro','CRIT Rate / CRIT DMG','Electric DMG','ATK','Enter Burst Mode with enough Energy to complete the useful attacks. Maintain Shock for the Thunder Metal plan rather than assuming permanent uptime.'],
 ['grace','weeping-gemini','thunder-metal','puffer-electro','Anomaly Proficiency','PEN / Electric DMG / ATK','Anomaly Mastery','Build and spend Zap; align important buildup with Shock uptime for this set. Chaos Jazz is an alternative when the team cannot sustain that condition.'],
 ['soukaku','bashful-demon','moonlight-lullaby','hormone-punk','ATK','ATK / Ice DMG','Energy Regen / ATK','Prepare Fly the Flag and pass the buff to the intended carry. Choose squad order around the assist recipient.'],
 ['yanagi','weeping-gemini','chaos-jazz','feathered-fate','Anomaly Proficiency','PEN / Electric DMG','Anomaly Mastery','Maintain both stance benefits and time EX attacks around the active Anomaly. Split field time deliberately in a two-carry team.'],
 ['qingyi','steam-oven','king-summit','shockstar-disco','CRIT Rate','Electric DMG / ATK','Impact','Build her enhanced Basic resources and stun amplification before handing off to a burst carry. Avoid letting preparation consume the useful stun window.'],
 ['seth','original-transmorpher','astral-voice','swing-jazz','ATK / Anomaly Proficiency','ATK / Electric DMG','Energy Regen / Anomaly Mastery','Place the intended shield recipient before Seth and use the backward assist hand-off. Original Transmorpher is a utility fallback, not his strongest shield engine.'],
 ['lucy','swing-cannon','moonlight-lullaby','puffer-electro','ATK','ATK','Energy Regen / ATK','Apply Cheer On close to the carry’s damage period. Reach the buff’s ATK requirement at your actual skill level before investing in personal CRIT.'],
 ['caesar','original-transmorpher','astral-voice','shockstar-disco','CRIT Rate / Anomaly Proficiency','Physical DMG / ATK','Impact','Parry and renew protection before the carry commits. Coordinate Quick Assists to activate Astral Voice rather than equipping it without an assist plan.'],
 ['burnice','weeping-gemini','chaos-jazz','moonlight-lullaby','Anomaly Proficiency','PEN / Fire DMG','Anomaly Mastery','Establish Scorched and maintain Heat while another Agent triggers off-field Fire. Refresh before the next burst rather than during it.'],
 ['lighter','steam-oven','king-summit','shockstar-disco','CRIT Rate','ATK / Fire DMG / PEN','Impact','Build Morale and prepare the stun hand-off. Spend the Fire or Ice carry’s attacks while the resistance and damage buffs overlap.'],
 ['astra-yao','swing-cannon','astral-voice','moonlight-lullaby','ATK','ATK','Energy Regen / ATK','Prepare the singing state, then cycle Quick Assists into the intended damage dealer. Build enough ATK for the support cap before chasing optional personal damage.'],
 ['yixuan','puzzle-sphere','yunkui-tales','woodpecker-electro','CRIT Rate / CRIT DMG','Ether DMG / HP','HP','Plan Adrenaline and Technique resources for the burst. Energy Regen does not improve Adrenaline; Sheer damage needs its own model.'],
 ['claret','crimson-thirst','thorned-rose','puffer-electro','CRIT Rate','PEN Ratio','DEF','Enter Crimson Inscription, build Gash and consume it through the enhanced Specials to trigger Maim. DEF scaling and CRIT conversion make generic Attack builds unsuitable.'],
 ['roxy','steam-oven','king-summit','moonlight-lullaby','CRIT Rate','PEN / Wind DMG / ATK','Energy Regen','Use EX sequences to manage Wind Energy and the intended Contamination attribute. On Armorer teams replace the CRIT-oriented four-piece with Astral Voice.'],
 ['promeia','weeping-gemini','notes-chained','phaethon-melody','Anomaly Proficiency','Ice DMG / ATK','Anomaly Mastery','Build Corrosive Chill through the team’s anomaly activity, then use Abloom EX in valuable damage periods. Start the set effect before a burst when resources allow.'],
 ['remielle','weeping-gemini','feathered-fate','chaos-jazz','Anomaly Proficiency','ATK','ATK','Enter Phase Flow, let teammates generate Voidflares, then use her swap-in Assist and finish the stored resources with enhanced Basics. Do not reset unspent Voidflares.'],
 ['sigrid','starlight-engine','hormone-punk','puffer-electro','CRIT DMG / ATK','PEN Ratio','ATK','Alternate stance-refreshing Unbridled Spear attacks with enhanced Basics. Save the stronger sequence for stun and account for her large in-combat CRIT Rate gain.'],
];
export const extraBuilds:BuildVariant[]=rows.map(([agentId,e,d1,d2,s4,s5,s6,rotation])=>{const a=agents.find(a=>a.id===agentId)!;return {id:`${agentId}-field-build`,kind:'build',agentId,modeId:'shiyu-defense',name:`${a.name} · field build`,summary:`A ${a.specialty} equipment plan with rotation notes and mode adjustments.`,patch:CURRENT_PATCH,status:'editorial',tags:[a.attribute,a.specialty,'Field build'],related:[agentId,'shiyu-defense','deadly-assault','hollow-zero',e,d1,d2],engineIds:[e],discIds:[d1,d2],discPlan:[{id:d1,pieces:4},{id:d2,pieces:2}],mainStats:{slot4:s4,slot5:s5,slot6:s6},substats:a.specialty==='Anomaly'?['Anomaly Proficiency','ATK']:a.specialty==='Support'?['ATK toward the relevant buff cap','Energy for uptime']:['Useful main-stat threshold','CRIT balance','Relevant scaling stat'],teamIds:teams.filter(t=>t.agentIds.includes(agentId)).map(t=>t.id),goal:a.fieldRole==='Carry'?'Consistent damage':'Enable the carry',rotation,priorities:['Finish the main stats and set conditions.','Upgrade the skills used by this rotation.','Test support uptime before chasing premium equipment.'],modeNotes:['Shiyu Defense: coordinate wave transitions and the second squad.','Deadly Assault: evaluate repeated rotations and distribute supports across three squads.','Hollow Zero: adapt to acquired programs rather than copying a timed-boss rotation unchanged.'],caveat:'Community-backed equipment starting point with original tactical notes. No measured damage ranking is claimed. Verify team-specific conditions and current kit upgrades.',source:profileSource(agentId),sourceReviewedIn:({anby:'2.0',lycaon:'2.6',anton:'1.5','astra-yao':'2.2',yixuan:'2.5',claret:'3.2',roxy:'3.2',promeia:'2.8',remielle:'3.1',sigrid:'3.1',nekomata:'3.1',burnice:'2.5'} as Record<string,string>)[agentId],verifiedAt:VERIFIED_AT}});
