import type {AuthoredGuide} from '../guide-schema';
export const caesarGuide:AuthoredGuide={
 agentId:'caesar',summary:'Build protection around Impact, choose discs for the assists you actually use and return field time to the protected carry.',
 catalogPatch:'3.2',revision:1,updatedAt:'2026-10-05',factsCheckedAt:'2026-10-05',equipmentCheckedAt:'2026-10-05',rotationTestedAt:null,modesTestedAt:null,
 assumptions:'M0 defensive-support baseline. Proto Punk assumes recurring Perfect Assists. No automatic shield on entry from Mindscape upgrades is assumed.',
 baseline:{discPlan:[{id:'proto-punk',pieces:4},{id:'shockstar-disco',pieces:2}],engineIds:['tusks-of-fury','original-transmorpher'],mainStats:{slot4:'CRIT Rate; AP for an Anomaly-focused plan',slot5:'Physical DMG or ATK',slot6:'Impact'},substats:['CRIT / ATK for personal damage','Anomaly Proficiency only for a defined Anomaly role']},
 choices:[
  {recordId:'proto-punk',when:'Baseline when the squad triggers Perfect Assists regularly. Its shield bonus and assist-triggered team buff serve this specific defensive plan.',sourceIds:['iv']},
  {recordId:'shockstar-disco',when:'Two pieces for Impact. Do not replace this with an HP pair merely because Caesar is a Defense Agent.',sourceIds:['iv']},
  {recordId:'astral-voice',when:'Alternative when the carry reliably uses Quick Assists and another teammate does not already provide the same effect. Ordinary swaps do not build its stacks.',sourceIds:['pr']},
  {recordId:'tusks-of-fury',when:'Signature option if owned. Reassess the shield plan with its Impact and shield benefits; owning it is not required to use this guide.',sourceIds:['iv']},
  {recordId:'original-transmorpher',when:'Accessible fallback. Its conditional combat Impact does not increase the shield’s initial-Impact scaling; do not count it as a permanent shield upgrade.',sourceIds:['iv']},
 ],
 sections:[
  {id:'direction',title:'Protection should buy uninterrupted carry time',text:'Radiant Aegis scales with initial Impact. Caesar’s job here is to establish protection and buffs, then give the field back. HP investment alone does not follow that shield scaling.',sourceIds:['kit']},
  {id:'equipment',title:'Choose the trigger, then the set',text:'Sources emphasize different defaults: Prydwen favors an assist-driven Astral Voice plan, while Icy Veins presents Proto Punk for protection and Perfect Assists. This guide chooses Proto Punk under the stated assumptions, not a universal winner.',sourceIds:['pr','iv']},
  {id:'rotation',title:'Rotation and resource management',text:'Against an incoming attack, time EX Parry Counter into Perfect Block, then use the Overpowered Shield Bash follow-up. After establishing Radiant Aegis, switch to the carry.',steps:['Identify an incoming attack rather than waiting indefinitely for a perfect opportunity.','Complete the counter/follow-up and confirm protection is active.','Return to the damage dealer; use Caesar again when protection or setup needs renewal.','During a passive boss phase, compare the cost of waiting for a counter with continuing the squad’s normal damage plan.'],sourceIds:['kit']},
  {id:'teams',squadIds:["soldier-11","lighter","caesar"],title:'Separate the shield role from additional ability checks',text:'Her additional ability can be enabled by a faction partner or another Agent with Defensive Assist. Use the planner for that check. A concrete starting squad is Soldier 11 / Lighter / Caesar: prepare Lighter’s stun, establish Caesar’s protection and return to Soldier 11. It is a source-listed composition, not a measured ranking.',sourceIds:['pr','teams'],relatedIds:['soldier-11','lighter','guide-activation']},
  {id:'shiyu-defense',title:'Shiyu Defense: track interruptions',text:'Editorial practice: count carry sequences interrupted with and without Caesar. Compare both sides’ clear times before assigning her to a side that already stays safe.',sourceIds:[],editorial:true},
  {id:'deadly-assault',title:'Deadly Assault: match the boss’s attack rhythm',text:'Editorial practice: record how much time is spent waiting to counter. If the boss rarely attacks, reassess the planned assist triggers before blaming the damage dealer’s equipment.',sourceIds:[],editorial:true},
  {id:'hollow-zero',title:'Hollow Zero: protect the expensive commitment',text:'Editorial practice: renew protection before the attack sequence you cannot comfortably interrupt. Compare survival and completed sequences, not just the size of the shield number.',sourceIds:[],editorial:true},
  {id:'mistakes',title:'Mistakes to catch',text:'Avoid HP-first farming for this shield, counting conditional Impact as initial Impact, and selecting Astral Voice without a Quick Assist route. A matching specialty does not guarantee the intended equipment interaction.',sourceIds:['iv','pr']},
 ],
 sources:[{id:'teams',title:'Icy Veins — Caesar team examples',url:'https://www.icy-veins.com/zenless-zone-zero/caesar-king-teams',checkedAt:'2026-10-05',scope:'Soldier 11 / Lighter / Caesar composition',revisionNote:'A source-listed example, not an Archive performance test.'},{id:'kit',title:'Icy Veins — skill reference',url:'https://www.icy-veins.com/zenless-zone-zero/caesar-king-profile-skills-mindscapes',checkedAt:'2026-10-05',scope:'Resource rules and skill triggers',revisionNote:'Skill reference only; no encounter performance test.'},{id:'pr',title:'Prydwen — Caesar equipment and conditions',url:'https://www.prydwen.gg/zenless/characters/caesar/',checkedAt:'2026-10-05',scope:'Astral Voice alternative, disc stats and additional-ability condition',revisionNote:'Its generalist set preference differs from the defensive baseline here; the trigger assumptions are shown explicitly.'},{id:'iv',title:'Icy Veins — Caesar build and shield loop',url:'https://www.icy-veins.com/zenless-zone-zero/caesar-king-guide-best-builds',checkedAt:'2026-10-05',scope:'Shield scaling, engine caveat, Proto Punk and counter sequence',revisionNote:'Page updated 2026-07-28 for 3.1. Reading it today does not establish a 3.2 performance test.'}],
 dependencies:['soldier-11','lighter','caesar','proto-punk','shockstar-disco','astral-voice','tusks-of-fury','original-transmorpher','shiyu-defense','deadly-assault','hollow-zero'],
 openQuestions:['No measured Soldier 11 / Lighter / Caesar rotation for the current stages.','No measured comparison of Proto Punk and Astral Voice under equal assist uptime.'],changelog:[{date:'2026-10-05',note:'Added an explicit defensive baseline and distinguished initial from conditional combat Impact.'}],
};
