import type {AuthoredGuide} from '../guide-schema';
export const lycaonGuide:AuthoredGuide={
 agentId:'lycaon',summary:'An Ice stun-support plan with a 50% CRIT set condition, a deliberate carry hand-off and a separate branch for awakened Potential.',
 catalogPatch:'3.2',revision:1,updatedAt:'2026-10-05',factsCheckedAt:'2026-10-05',equipmentCheckedAt:'2026-10-05',rotationTestedAt:null,modesTestedAt:null,
 assumptions:'M0. The ordinary charged-attack loop and Potential-awakened loop are distinguished below. King of the Summit assumes a carry that benefits from CRIT DMG.',
 baseline:{discPlan:[{id:'king-summit',pieces:4},{id:'shockstar-disco',pieces:2}],engineIds:['restrained','steam-oven'],mainStats:{slot4:'CRIT Rate until 50% for King of the Summit',slot5:'Ice DMG or ATK',slot6:'Impact'},substats:['CRIT Rate to the set condition','CRIT DMG / ATK after utility is established']},
 choices:[
  {recordId:'king-summit',when:'Four pieces for a CRIT carry. Meet 50% CRIT Rate and trigger the team bonus with EX or Chain; do not farm CRIT DMG first.',sourceIds:['iv']},
  {recordId:'shockstar-disco',when:'Two pieces supply Impact. A four-piece stun-focused alternative needs evidence that it changes a useful stun timing.',sourceIds:['pr','iv']},
  {recordId:'restrained',when:'Use if already owned and playing charged Basics. Recheck its value if you move most of Lycaon’s work to assist windows.',sourceIds:['iv'],},
  {recordId:'steam-oven',when:'Accessible Stun candidate. Evaluate the Energy cycle together with EX use rather than treating maximum passive stacks as permanent.',sourceIds:['iv']},
 ],
 sections:[
  {id:'direction',title:'Prepare the carry’s opening',text:'Lycaon combines Daze with Ice resistance reduction and an additional-ability stun multiplier. A fast stun is useful only when the carry can spend it. Choose his field time around that hand-off.',sourceIds:['pr']},
  {id:'equipment',title:'Meet the support-set condition first',text:'The baseline supports an Ice CRIT carry. Slot 6 stays Impact; slot 4 establishes the King of the Summit condition. An Armorer or other non-CRIT damage plan requires a different support-set review.',sourceIds:['iv']},
  {id:'rotation',title:'Rotation and resource management',text:'Without awakened Potential, use charged Basics and EX/assist follow-ups to prepare stun. With Potential, Glacial Waltz can enable Encircle Prey and a backward Quick Assist; placing the carry before Lycaon makes that hand-off usable.',steps:['Check whether Potential is unlocked before following the awakened branch.','Establish the relevant EX/assist debuff, then build the needed Daze.','For the awakened branch, take the backward Quick Assist into the intended attacker.','Encircle Prey can end early on a Chain, Ultimate or an attack pause; do not assume it always lasts the full duration.','Once the carry’s window is ready, stop extending Lycaon’s setup.'],sourceIds:['pr']},
  {id:'teams',squadIds:["miyabi","lycaon","soukaku"],title:'Pick an Ice carry or a faction partner',text:'Ellen / Lycaon / Soukaku is an Ice stun composition. Miyabi / Lycaon / Soukaku gives Miyabi a stun-focused alternative to Disorder. Corin can satisfy a faction pairing, but her Physical damage does not use the Ice resistance reduction.',sourceIds:['pr'],relatedIds:['ellen-core','miyabi-ice','corin-victoria']},
  {id:'shiyu-defense',title:'Shiyu Defense: measure the hand-off',text:'Editorial practice: compare runs where the carry enters immediately after setup against runs with one extra Lycaon string. Record clear time and carry resources, not just time-to-stun.',sourceIds:[],editorial:true},
  {id:'deadly-assault',title:'Deadly Assault: keep the Potential branch consistent',text:'Editorial practice: log why each coordinated-attack window ends. An early Ultimate may be intentional, but an accidental attack pause should not be mistaken for poor disc performance.',sourceIds:[],editorial:true},
  {id:'hollow-zero',title:'Hollow Zero: let encounter length guide setup',text:'Editorial practice: on short encounters, test whether elaborate stun preparation delays a simpler carry finish. Keep the longer setup for targets that survive it.',sourceIds:[],editorial:true},
  {id:'mistakes',title:'Mistakes to catch',text:'Avoid a sub-50% CRIT support set, the wrong backward-assist recipient, and an awakened rotation on a non-awakened kit. These are distinct checks; passing one does not establish the others.',sourceIds:['iv','pr']},
 ],
 sources:[{id:'pr',title:'Prydwen — Lycaon kit and Potential',url:'https://www.prydwen.gg/zenless/characters/lycaon/',checkedAt:'2026-10-05',scope:'Potential branch, assist direction and squad interactions',revisionNote:'Profile updated 2026-09-30; review/build/team tracker still identifies patch 2.6. This is not a fresh damage test.'},{id:'iv',title:'Icy Veins — Lycaon equipment',url:'https://www.icy-veins.com/zenless-zone-zero/von-lycaon-guide-best-builds',checkedAt:'2026-10-05',scope:'King of the Summit requirements, disc stats and listed engine candidates',revisionNote:'Equipment candidates are not an exhaustive or measured engine ranking.'}],
 dependencies:['lycaon','ellen','miyabi','corin','soukaku','king-summit','shockstar-disco','restrained','steam-oven','shiyu-defense','deadly-assault','hollow-zero'],
 openQuestions:['No controlled comparison of awakened versus non-awakened rotations.','No proof that a four-piece Daze set adds a useful stun on current bosses.'],changelog:[{date:'2026-10-05',note:'Separated Potential behavior from the ordinary kit and made the support-set threshold explicit.'}],
};
