import type {AuthoredGuide} from '../guide-schema';
export const miyabiGuide:AuthoredGuide={
 agentId:'miyabi', summary:'Build around CRIT and Fallen Frost: a six-stack spending rule, conditional equipment choices and two distinct team plans.',
 catalogPatch:'3.2',revision:1,updatedAt:'2026-10-05',factsCheckedAt:'2026-10-05',equipmentCheckedAt:'2026-10-05',rotationTestedAt:null,modesTestedAt:null,
 assumptions:'M0 baseline. No signature W-Engine or fixed stage modifier assumed. This is source-checked editorial guidance; no timed run or damage comparison has been performed.',
 baseline:{discPlan:[{id:'branch-blade',pieces:4},{id:'polar-metal',pieces:2}],engineIds:['hailstorm-shrine','weeping-gemini'],mainStats:{slot4:'CRIT Rate; CRIT DMG after the threshold',slot5:'Ice DMG or ATK',slot6:'ATK'},substats:['CRIT Rate to 80% in combat','CRIT DMG / ATK','Avoid exceeding 100% CRIT Rate']},
 choices:[
  {recordId:'branch-blade',when:'Use four pieces as the baseline. Count its conditional CRIT Rate when deciding whether slot 4 still needs CRIT Rate.',sourceIds:['iv']},
  {recordId:'polar-metal',when:'Two pieces complete the six-slot plan. Compare ATK alternatives using the pieces you already own before farming a replacement.',sourceIds:['pr']},
  {recordId:'hailstorm-shrine',when:'If owned, its CRIT-oriented stats fit Miyabi. Recalculate slot 4 after equipping it.',sourceIds:['pr']},
  {recordId:'weeping-gemini',when:'Craftable fallback. It does not replace the signature’s CRIT stats; preserve the CRIT target with discs.',sourceIds:['pr']},
 ],
 sections:[
  {id:'direction',title:'A CRIT carry with an Anomaly resource loop',text:'Miyabi converts CRIT Rate into Frost buildup, capped at 80% CRIT Rate for that conversion. Further CRIT Rate can still improve critical hits. Do not copy an Anomaly Proficiency main-stat plan solely because her specialty says Anomaly.',sourceIds:['iv'],relatedIds:['guide-frost']},
  {id:'equipment',title:'Equipment decisions',text:'Use the baseline below, then inspect in-combat bonuses. Changing an engine can change the right slot-4 choice without changing the rest of the build.',sourceIds:['iv','pr']},
  {id:'rotation',title:'Rotation and resource management',text:'Use the six-Fallen-Frost charged attack as the decision point. EX casts grant two stacks; the Ultimate grants three. Avoid generating resources into the cap.',steps:['Check the stack count before committing Energy.','At six stacks, fully charge Shimotsuki; do not release an incomplete charge by habit.','Below six, use an EX or, with the additional ability active, a partner’s Disorder to finish the resource cycle.','Return to the partner when further Miyabi field time would delay the next useful Disorder.'],sourceIds:['kit']},
  {id:'teams',squadIds:["miyabi","yanagi","soukaku"],title:'Choose a resource plan',text:'Miyabi / Yanagi / Soukaku uses Disorder to feed the loop. Miyabi / Lycaon / Soukaku instead concentrates damage around stun. Switching between them changes the hand-off timing; it does not automatically require a different disc farm.',sourceIds:['pr'],relatedIds:['miyabi-disorder','miyabi-ice']},
  {id:'shiyu-defense',title:'Shiyu Defense: carry resources into the next wave',text:'Editorial practice: if a wave is nearly finished, compare a short cleanup against spending the full charged attack. Record whether the saved charge gives a cleaner opening on the next spawn.',sourceIds:[],editorial:true},
  {id:'deadly-assault',title:'Deadly Assault: audit the second cycle',text:'Editorial practice: after the opener, count how often you wait below six stacks. Adjust the partner hand-off before replacing equipment. One strong opening can hide a stalled repeating cycle.',sourceIds:[],editorial:true},
  {id:'hollow-zero',title:'Hollow Zero: keep one baseline',text:'Editorial practice: keep the same loadout and record which acquired effect changes your spending decision. Do not describe that run-specific change as a permanent build upgrade.',sourceIds:[],editorial:true},
  {id:'mistakes',title:'Mistakes to catch',text:'Watch for resource overflow, CRIT overcapping and switching to an Anomaly Proficiency disc without a specific reason. Try one correction per run so its effect remains observable.',sourceIds:['iv','pr']},
 ],
 sources:[{id:'kit',title:'Icy Veins — skill reference',url:'https://www.icy-veins.com/zenless-zone-zero/hoshimi-miyabi-profile-skills-mindscapes',checkedAt:'2026-10-05',scope:'Resource rules and skill triggers',revisionNote:'Skill reference only; no encounter performance test.'},{id:'pr',title:'Prydwen — Miyabi kit, equipment and teams',url:'https://www.prydwen.gg/zenless/characters/miyabi/',checkedAt:'2026-10-05',scope:'Fallen Frost loop, engine candidates and squad archetypes',revisionNote:'Source profile and build revisions are separate; this check does not establish a patch-3.2 performance test.'},{id:'iv',title:'Icy Veins — Miyabi build',url:'https://www.icy-veins.com/zenless-zone-zero/hoshimi-miyabi-guide-best-builds',checkedAt:'2026-10-05',scope:'CRIT threshold, main stats and disc choices',revisionNote:'Page reports an update on 2026-04-09; current encounter performance remains untested here.'}],
 dependencies:['miyabi','yanagi','soukaku','lycaon','branch-blade','polar-metal','hailstorm-shrine','weeping-gemini','shiyu-defense','deadly-assault','hollow-zero'],
 openQuestions:['No measured comparison of ATK versus Ice DMG slot 5 for a fixed squad.','No boss-specific timings for the currently rotating stages.'],
 changelog:[{date:'2026-10-05',note:'Replaced generated advice with a resource-based guide; separated source checks from gameplay testing.'}],
};
