import type {AuthoredGuide} from '../guide-schema';
export const nicoleGuide:AuthoredGuide={
 agentId:'nicole',summary:'Refresh a short defense debuff exactly when the carry needs it. Includes an Energy-first build and a practical Zhu Yuan hand-off.',
 catalogPatch:'3.2',revision:1,updatedAt:'2026-10-05',factsCheckedAt:'2026-10-05',equipmentCheckedAt:'2026-10-05',rotationTestedAt:null,modesTestedAt:null,
 assumptions:'Base support loop; M6 CRIT bonuses are not assumed. The Zhu Yuan example is a sequencing baseline, not a tested boss rotation.',
 baseline:{discPlan:[{id:'moonlight-lullaby',pieces:4},{id:'swing-jazz',pieces:2}],engineIds:['vault','swing-cannon'],mainStats:{slot4:'Anomaly Proficiency',slot5:'Ether DMG',slot6:'Energy Regen'},substats:['Anomaly Proficiency','ATK','Personal damage after reliable EX access']},
 choices:[
  {recordId:'moonlight-lullaby',when:'Baseline squad buff with an EX/Ultimate trigger. Check whether another teammate already carries the same non-stacking effect.',sourceIds:['iv']},
  {recordId:'swing-jazz',when:'Two pieces for Energy Regen. Choose repeatable EX access before improving Nicole’s personal damage.',sourceIds:['iv']},
  {recordId:'astral-voice',when:'Alternative four-piece set when the intended carry repeatedly enters through Quick Assist. Do not assume full stacks from ordinary switching.',sourceIds:['iv']},
  {recordId:'vault',when:'A natural fit for her Ether field and support cycle. Compare at the refinement you own rather than borrowing a source’s S5 result.',sourceIds:['pr']},
  {recordId:'swing-cannon',when:'General support fallback if The Vault is unavailable. Check the actual passive trigger and refinement on your copy.',sourceIds:['pr']},
 ],
 sections:[
  {id:'direction',title:'The last hit starts the debuff clock',text:'Nicole’s defense reduction lasts 3.5 seconds from the last qualifying hit. Her field can refresh it while hitting. Plan around that final refresh, not merely the moment you press EX.',sourceIds:['pr']},
  {id:'equipment',title:'Energy before personal damage',text:'The listed main stats give a usable support baseline. Nicole’s personal damage is secondary to having an EX when the next carry window starts. A missing EX is a rotation problem that extra offensive substats cannot repair.',sourceIds:['iv']},
  {id:'rotation',title:'Rotation and resource management',text:'With Zhu Yuan, prepare the stunner first and apply Nicole’s field near the damage hand-off. Use a short EX by default; longer application is a deliberate Anomaly choice, not a mandatory delay.',steps:['Check that Nicole has Energy before committing to the next stun.','Place the field on the actual target, then take the carry’s Quick Assist.','Spend the carry’s prepared burst while the field/debuff covers it.','If another major burst remains, refresh through an available EX, Chain or Ultimate at a safe hand-off.','Avoid staying on Nicole just to force perfect uptime during low-value attacks.'],sourceIds:['pr']},
  {id:'teams',squadIds:["zhu-yuan","anby","nicole"],title:'Ether benefit and general defense reduction',text:'Zhu Yuan / Anby / Nicole is an accessible catalog example; Qingyi is the alternative stunner. Her extra Ether benefit has an attribute/faction condition. General defense reduction and that additional benefit are separate checks.',sourceIds:['pr'],relatedIds:['zhu-accessible','zhu-premium','guide-activation']},
  {id:'shiyu-defense',title:'Shiyu Defense: group before committing',text:'Editorial practice: compare where the field lands against where the next wave actually gathers. Repositioning once before the carry commits may be better than chasing scattered survivors afterward.',sourceIds:[],editorial:true},
  {id:'deadly-assault',title:'Deadly Assault: inspect the expensive attacks',text:'Editorial practice: review whether the carry’s largest attacks land after the last debuff refresh. Track missed coverage before trying to increase Nicole’s personal damage.',sourceIds:[],editorial:true},
  {id:'hollow-zero',title:'Hollow Zero: preserve EX for the next threat',text:'Editorial practice: if a small group will die to the carry’s existing resources, try carrying Nicole’s Energy forward. Compare the next elite opening rather than only the current room.',sourceIds:[],editorial:true},
  {id:'mistakes',title:'Mistakes to catch',text:'A field cast too early, an unnecessary long charge and unearned Astral Voice stacks can all weaken the hand-off. Check each separately before replacing the support.',sourceIds:['pr','iv']},
 ],
 sources:[{id:'pr',title:'Prydwen — Nicole kit and execution',url:'https://www.prydwen.gg/zenless/characters/nicole-demara/',checkedAt:'2026-10-05',scope:'Debuff timing, field refreshes, engine candidates and hand-offs',revisionNote:'Profile updated 2026-09-09; review/build/team trackers show 2.4 / 2.2 / 2.5. Those dates are not replaced by this source check.'},{id:'iv',title:'Icy Veins — Nicole equipment',url:'https://www.icy-veins.com/zenless-zone-zero/nicole-demara-guide-best-builds',checkedAt:'2026-10-05',scope:'Moonlight/Swing Jazz baseline, alternative set and main stats',revisionNote:'Page reports an update on 2025-11-25. Recommendations are a baseline, not proof of current-stage optimality.'}],
 dependencies:['nicole','zhu-yuan','anby','qingyi','moonlight-lullaby','swing-jazz','astral-voice','vault','swing-cannon','shiyu-defense','deadly-assault','hollow-zero'],
 openQuestions:['No measured minimum Energy Regen for a fixed rotation.','No timed comparison of short versus charged EX on a current boss.'],changelog:[{date:'2026-10-05',note:'Replaced the generic equipment paragraph with an Energy-first baseline and short-debuff decision rules.'}],
};
