import type {AuthoredGuide} from '../guide-schema';
export const zhuYuanGuide:AuthoredGuide={
 agentId:'zhu-yuan',summary:'Prepare Enhanced Shotshells, align Nicole’s debuff with stun and spend the burst without wasting ammunition or CRIT Rate.',
 catalogPatch:'3.2',revision:1,updatedAt:'2026-10-05',factsCheckedAt:'2026-10-05',equipmentCheckedAt:'2026-10-05',rotationTestedAt:null,modesTestedAt:null,
 assumptions:'M0 burst plan with Nicole and a stunner. No signature engine assumed. Fixed frame counts and current-stage scores have not been tested.',
 baseline:{discPlan:[{id:'chaotic-metal',pieces:4},{id:'woodpecker-electro',pieces:2}],engineIds:['riot-suppressor','starlight-engine'],mainStats:{slot4:'CRIT DMG or ATK after accounting for combat CRIT',slot5:'ATK; compare Ether DMG for your squad',slot6:'ATK'},substats:['CRIT Rate after combat buffs','CRIT DMG','ATK']},
 choices:[
  {recordId:'chaotic-metal',when:'Use with an Ether application plan, such as Nicole. Its conditional bonus needs Corruption; the set name alone does not guarantee uptime.',sourceIds:['pr']},
  {recordId:'woodpecker-electro',when:'Two pieces supply CRIT Rate. Count all combat buffs before keeping this pair solely for its stat.',sourceIds:['iv']},
  {recordId:'riot-suppressor',when:'If owned, include its CRIT contribution when choosing main stats; do not reuse a budget loadout unchanged.',sourceIds:['pr']},
  {recordId:'starlight-engine',when:'Budget candidate. Enter through Quick Assist or use a Dodge Counter to establish its ATK effect before the burst.',sourceIds:['pr']},
 ],
 sections:[
  {id:'direction',title:'Reserve the burst for a prepared target',text:'Enhanced Shotshells are capped at nine. Holding Basic spends them in Suppression Mode, where the enhanced attacks gain additional value against stunned targets. Empty-shell holding is not the same attack plan.',sourceIds:['iv']},
  {id:'equipment',title:'Count CRIT where the damage happens',text:'Zhu Yuan gains combat CRIT through her additional ability. Include that and equipment or teammate buffs before adding more CRIT Rate. A sheet-only target can overshoot during the actual burst.',sourceIds:['pr']},
  {id:'rotation',title:'Rotation and resource management',text:'This is a resource-gated baseline, not a frame-perfect combo. EX, Chain and Ultimate provide ammunition; spend shells before a refill would exceed the cap.',steps:['Prepare ammunition while the stunner builds Daze.','Apply Nicole’s field close to the burst and enter Zhu Yuan through the available assist.','Spend enhanced held Basics during stun.','Use a refill when ammunition is low, then resume enhanced fire while the window remains.','Leave Suppression Mode when shells are gone; restart setup instead of holding unenhanced fire.'],sourceIds:['kit']},
  {id:'teams',squadIds:["zhu-yuan","qingyi","nicole"],title:'Keep the support hand-off intact',text:'Zhu Yuan / Qingyi / Nicole is the catalog stun team. Anby replaces Qingyi in the accessible composition. The replacement changes stun preparation, so learn that timing again rather than expecting the same burst schedule.',sourceIds:['pr'],relatedIds:['zhu-premium','zhu-accessible']},
  {id:'shiyu-defense',title:'Shiyu Defense: spend only what the wave needs',text:'Editorial practice: note shell count at each wave transition. If the first group dies halfway through a burst, stop and aim the next sequence instead of continuing into empty space.',sourceIds:[],editorial:true},
  {id:'deadly-assault',title:'Deadly Assault: inspect missed burst windows',text:'Editorial practice: separate failed attempts into late stun, low ammunition and expired support setup. Fix the most frequent category before changing discs.',sourceIds:[],editorial:true},
  {id:'hollow-zero',title:'Hollow Zero: distinguish run bonuses from your build',text:'Editorial practice: record any program that changes resource availability. Evaluate that run separately from the normal EX-and-refill schedule.',sourceIds:[],editorial:true},
  {id:'mistakes',title:'Mistakes to catch',text:'Do not enter a long held-Basic sequence with no shells, refill at nine shells, or spend the stun window completing support setup. These errors can survive an equipment upgrade.',sourceIds:['pr','iv']},
 ],
 sources:[{id:'kit',title:'Icy Veins — skill reference',url:'https://www.icy-veins.com/zenless-zone-zero/zhu-yuan-profile-skills-mindscapes',checkedAt:'2026-10-05',scope:'Resource rules and skill triggers',revisionNote:'Skill reference only; no encounter performance test.'},{id:'pr',title:'Prydwen — Zhu Yuan kit and build',url:'https://www.prydwen.gg/zenless/characters/zhu-yuan/',checkedAt:'2026-10-05',scope:'Shell spending, additional ability, engine triggers and teams',revisionNote:'Source recommendations are contextual; no global engine or team ranking is reproduced.'},{id:'iv',title:'Icy Veins — Zhu Yuan build',url:'https://www.icy-veins.com/zenless-zone-zero/zhu-yuan-guide-best-builds',checkedAt:'2026-10-05',scope:'Shell cap, stun role and stat priorities',revisionNote:'Some recommendations assume partners outside this catalog; this guide covers the stated Nicole/stunner baseline.'}],
 dependencies:['zhu-yuan','nicole','qingyi','anby','chaotic-metal','woodpecker-electro','riot-suppressor','starlight-engine','shiyu-defense','deadly-assault','hollow-zero'],
 openQuestions:['No measured shell-by-shell route for a specific current boss.','Disc alternatives for Dialyn teams are outside this guide’s scope.'],changelog:[{date:'2026-10-05',note:'Added shell-cap decisions and a Nicole/stunner baseline; consolidated mode advice into one guide.'}],
};
